// <auto-generated />
using System;
using GestionComercial.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionComercial.Persistencia.Migrations
{
    [DbContext(typeof(GestionComercialContext))]
    [Migration("20260511000001_ViewsAndTriggers")]
    partial class ViewsAndTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // Las vistas se agregan al modelo, pero como entidades HasNoKey.
            // El modelo subyacente (tablas) es idéntico al de la migración anterior.
            // Las vistas son objetos de solo lectura mapeados via ToView().
            // No se incluyen en el snapshot porque no son entidades con clave primaria.
#pragma warning restore 612, 618
        }
    }
}