// <auto-generated />
using System;
using GestionComercial.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionComercial.Persistencia.Migrations
{
    [DbContext(typeof(GestionComercialContext))]
    [Migration("20260511000000_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
            // Esta migración solo modifica __EFMigrationsHistory, no el modelo de datos.
            // El modelo es idéntico al de ProveedorProductoCosto.
#pragma warning restore 612, 618
        }
    }
}