// <auto-generated />
using System;
using GestionComercial.Persistencia.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionComercial.Persistencia.Migrations
{
    [DbContext(typeof(GestionComercialContext))]
    partial class GestionComercialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Caja.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_sucursal")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioApertura_id")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCierre_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioApertura_id");

                    b.HasIndex("UsuarioCierre_id");

                    b.HasIndex("Id_sucursal", "Estado");

                    b.ToTable("Caja", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Caja.TipoMovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_caja")
                        .HasColumnType("int");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_caja");

                    b.HasIndex("Id_usuario");

                    b.ToTable("MovimientoCaja", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Cliente.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id_empresa");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Cliente.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Documento Nacional de Identidad",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4178),
                            Nombre = "DNI"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Clave Única de Identificación Tributaria",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4179),
                            Nombre = "CUIT"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Pasaporte",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4181),
                            Nombre = "Pasaporte"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Compras.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_proveedor")
                        .HasColumnType("int");

                    b.Property<int>("Id_sucursal")
                        .HasColumnType("int");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_proveedor");

                    b.HasIndex("Id_sucursal");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Compras.CompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Id_compra")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_compra");

                    b.HasIndex("Id_producto");

                    b.ToTable("CompraDetalle", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Movimientos.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<int>("Id_sucursal")
                        .HasColumnType("int");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockAnterior")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockNuevo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_sucursal");

                    b.HasIndex("Id_usuario");

                    b.HasIndex("Id_producto", "Fecha");

                    b.ToTable("MovimientoStock", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Movimientos.TipoMovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoMovimientoStock", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Ingreso de mercadería",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4139),
                            Nombre = "Entrada"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Egreso de mercadería",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4140),
                            Nombre = "Salida"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Ajuste positivo de stock",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4141),
                            Nombre = "Ajuste Positivo"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Ajuste negativo de stock",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4142),
                            Nombre = "Ajuste Negativo"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Organizacion.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CUIT")
                        .IsUnique();

                    b.ToTable("Empresa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CUIT = "20-12345678-9",
                            Direccion = "Dirección Principal 123",
                            Email = "admin@miempresa.com",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4424),
                            Nombre = "Mi Empresa",
                            Telefono = "3794000000"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id_empresa");

                    b.ToTable("Sucursal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Direccion = "Dirección Principal 123",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4459),
                            Id_empresa = 1,
                            Nombre = "Casa Central",
                            Telefono = "3794000000"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Pagos.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsEfectivo")
                        .HasColumnType("bit");

                    b.Property<int>("Id_empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id_empresa");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Pagos.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_metodoPago")
                        .HasColumnType("int");

                    b.Property<int>("Id_venta")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_metodoPago");

                    b.HasIndex("Id_venta");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaPadre_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadre_id");

                    b.HasIndex("Id_empresa");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("Id_empresa")
                        .HasColumnType("int");

                    b.Property<int>("Id_unidadMedida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCostoActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarra")
                        .IsUnique()
                        .HasFilter("[CodigoBarra] IS NOT NULL");

                    b.HasIndex("Id_categoria");

                    b.HasIndex("Id_empresa");

                    b.HasIndex("Id_unidadMedida");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedida", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Proveedores.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Id_empresa");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Permiso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Ver ventas",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4215),
                            Nombre = "Ventas.Ver"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Crear ventas",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4217),
                            Nombre = "Ventas.Crear"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Anular ventas",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4218),
                            Nombre = "Ventas.Anular"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Ver compras",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4219),
                            Nombre = "Compras.Ver"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Crear compras",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4221),
                            Nombre = "Compras.Crear"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Ver productos",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4222),
                            Nombre = "Productos.Ver"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Crear productos",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4223),
                            Nombre = "Productos.Crear"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Editar productos",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4224),
                            Nombre = "Productos.Editar"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Ver clientes",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4225),
                            Nombre = "Clientes.Ver"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Crear clientes",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4226),
                            Nombre = "Clientes.Crear"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Descripcion = "Ver reportes",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4228),
                            Nombre = "Reportes.Ver"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Descripcion = "Abrir caja",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4229),
                            Nombre = "Caja.Abrir"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Descripcion = "Cerrar caja",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4230),
                            Nombre = "Caja.Cerrar"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Descripcion = "Ver configuración",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4232),
                            Nombre = "Configuracion.Ver"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Descripcion = "Gestionar usuarios",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4233),
                            Nombre = "Usuarios.Gestionar"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Acceso total al sistema",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(3964),
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Administración general",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(3976),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Operaciones de venta",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(3977),
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_permiso")
                        .HasColumnType("int");

                    b.Property<int>("Id_rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_permiso");

                    b.HasIndex("Id_rol");

                    b.ToTable("RolPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4291),
                            Id_permiso = 1,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4293),
                            Id_permiso = 2,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4293),
                            Id_permiso = 3,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4294),
                            Id_permiso = 4,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4295),
                            Id_permiso = 5,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4295),
                            Id_permiso = 6,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4296),
                            Id_permiso = 7,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4297),
                            Id_permiso = 8,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4297),
                            Id_permiso = 9,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4298),
                            Id_permiso = 10,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4298),
                            Id_permiso = 11,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4299),
                            Id_permiso = 12,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4300),
                            Id_permiso = 13,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4300),
                            Id_permiso = 14,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4301),
                            Id_permiso = 15,
                            Id_rol = 1
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4342),
                            Id_permiso = 1,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4344),
                            Id_permiso = 2,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4344),
                            Id_permiso = 3,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4345),
                            Id_permiso = 4,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4346),
                            Id_permiso = 5,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4346),
                            Id_permiso = 6,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4347),
                            Id_permiso = 7,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4348),
                            Id_permiso = 8,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4348),
                            Id_permiso = 9,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4349),
                            Id_permiso = 10,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4350),
                            Id_permiso = 11,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4350),
                            Id_permiso = 12,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4351),
                            Id_permiso = 13,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4351),
                            Id_permiso = 14,
                            Id_rol = 2
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4379),
                            Id_permiso = 1,
                            Id_rol = 3
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4380),
                            Id_permiso = 2,
                            Id_rol = 3
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4382),
                            Id_permiso = 6,
                            Id_rol = 3
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4383),
                            Id_permiso = 9,
                            Id_rol = 3
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4384),
                            Id_permiso = 10,
                            Id_rol = 3
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4385),
                            Id_permiso = 12,
                            Id_rol = 3
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4386),
                            Id_permiso = 13,
                            Id_rol = 3
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_rol")
                        .HasColumnType("int");

                    b.Property<int>("Id_sucursal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id_rol");

                    b.HasIndex("Id_sucursal");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Sistema",
                            Email = "admin@sistema.com",
                            FechaAlta = new DateTime(2026, 3, 5, 0, 44, 31, 461, DateTimeKind.Local).AddTicks(4487),
                            Id_rol = 1,
                            Id_sucursal = 1,
                            Nombre = "Admin",
                            PasswordHash = "$2a$12$xTXms.c66F43LdABY4LZjeXhAJmZSwEeYircoRBHDnBy4cqkklYFu"
                        });
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Ventas.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_caja")
                        .HasColumnType("int");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_sucursal")
                        .HasColumnType("int");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFinal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Id_caja");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("Id_usuario");

                    b.HasIndex("Id_sucursal", "Fecha");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Ventas.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<int>("Id_venta")
                        .HasColumnType("int");

                    b.Property<decimal>("MargenUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_producto");

                    b.HasIndex("Id_venta");

                    b.ToTable("VentaDetalle", (string)null);
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Caja.Caja", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", "Sucursal")
                        .WithMany("Cajas")
                        .HasForeignKey("Id_sucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Usuario", "UsuarioApertura")
                        .WithMany()
                        .HasForeignKey("UsuarioApertura_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("UsuarioCierre_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sucursal");

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Caja.TipoMovimientoCaja", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Caja.Caja", "Caja")
                        .WithMany("Movimientos")
                        .HasForeignKey("Id_caja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Cliente.Cliente", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("Id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Compras.Compra", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Proveedores.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("Id_proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", "Sucursal")
                        .WithMany("Compras")
                        .HasForeignKey("Id_sucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Compras.CompraDetalle", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Compras.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Producto.Producto", "Producto")
                        .WithMany("CompraDetalles")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Movimientos.MovimientoStock", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Producto.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("Id_sucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("Id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Pagos.MetodoPago", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Empresa", "Empresa")
                        .WithMany("MetodosPago")
                        .HasForeignKey("Id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Pagos.Pago", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Pagos.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("Id_metodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Ventas.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("Id_venta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.Categoria", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Producto.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadre_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Empresa", "Empresa")
                        .WithMany("Categorias")
                        .HasForeignKey("Id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPadre");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.Producto", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Producto.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("Id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Producto.UnidadMedida", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("Id_unidadMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Proveedores.Proveedor", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Empresa", "Empresa")
                        .WithMany("Proveedores")
                        .HasForeignKey("Id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("Id_permiso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("Id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.Usuario", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_sucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Ventas.Venta", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Caja.Caja", "Caja")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_caja")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionComercial.Dominio.Entidades.Cliente.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", "Sucursal")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_sucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Cliente");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Ventas.VentaDetalle", b =>
                {
                    b.HasOne("GestionComercial.Dominio.Entidades.Producto.Producto", "Producto")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionComercial.Dominio.Entidades.Ventas.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Caja.Caja", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Cliente.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Compras.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Organizacion.Empresa", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Clientes");

                    b.Navigation("MetodosPago");

                    b.Navigation("Productos");

                    b.Navigation("Proveedores");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Organizacion.Sucursal", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("Compras");

                    b.Navigation("Usuarios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Pagos.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.Producto", b =>
                {
                    b.Navigation("CompraDetalles");

                    b.Navigation("Movimientos");

                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Producto.UnidadMedida", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Proveedores.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Seguridad.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestionComercial.Dominio.Entidades.Ventas.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
